---
title: A Title of Your Beautiful Presentation
subtitle: Based on Beautiful Work
format: clean-revealjs
author:
  - name: Your Name
    email: alias@email.com
    affiliations: Your Institution
---

## Example slide

### This is a subtitle

Here we have some text that may run over several lines of the slide frame, depending on how long it is.

-   first item
    -   A sub item

Next, we'll brief review some theme-specific components.

-   Note that *all* of the standard Reveal.js [features](https://quarto.org/docs/presentations/revealjs/) can be used with this theme, even if we don't highlight them here.

## Additional theme classes

### Some extra things you can do with the clean theme

Special classes for emphasis

-   `.alert` class for default emphasis, e.g. [important note]{.alert}.
-   `.fg` class for custom colour, e.g. [important note]{.fg style="--col: #e64173"}.
-   `.bg` class for custom background, e.g. [important note]{.bg style="--col: #e64173"}.
-   [highlight]{.hl style="--col: #33aa3355"}

Cross-references

-   `.button` class provides a Beamer-like button, e.g. [[Summary](#sec-summary)]{.button}

## Want more?

### See our longer demo slides

We've deliberarely kept this template lean, to get you up and running as fast as possible.

We provide a separate [demo template](https://github.com/grantmcdermott/quarto-revealjs-clean-demo), with more examples for integrating code, tables, figures, etc.

-   See the live demo slides [here](https://grantmcdermott.com/quarto-revealjs-clean-demo/template.html).

## Summary {#sec-summary}

### A minimalist and elegant presentation theme

The Quarto reveal.js clean theme aims to be a minimalist and elegant presention theme. Here are some options to get you started:

Add the theme to an existing project.

``` bash
quarto install extension grantmcdermott/quarto-revealjs-clean
```

... or, create a new project using this slide deck as a lean template.

``` bash
quarto use template grantmcdermott/quarto-revealjs-clean
```

... or, create a new project using the demo slide deck as a full template.

``` bash
quarto use template grantmcdermott/quarto-revealjs-clean-demo
```

## Columns

::::: columns
::: column
-   AAA

-   BBB

-   CCC
:::

::: column
Another column of text here

$$
f(x) = \sqrt{x^3+x^2+x+1}
$$
:::
:::::